version: '3'
services:
  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.tumit.ga
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.tumit.ga
      - LETSENCRYPT_EMAIL=tumit@odds.team
    network_mode: bridge